---
title: "PREPROCESSING - version.09.4"
author: "김민영"
date: "2022-12-03"
output: github_document
---

# 0.환경설정
```{r 패키지}
#rm(list=ls())
suppressPackageStartupMessages({
  require(googledrive)
  require(DataExplorer)
  require(dplyr)
  require(data.table)
  require(magrittr)
  require(imputeTS) 
  require(lubridate)
  require(caret)
  require(leaps) #회귀
  require(car) #회귀
})
drive_auth()
```

```{r 드라이브 세팅}

#1. train_input
train_in_id = drive_ls("2022_03/data",  pattern="train_input") $id
train_in_ls = drive_ls(path = as_id(train_in_id))
train_in_ls %<>% arrange(name)
final <- NULL
for (i in 1:nrow(train_in_ls)){
    drive_download(as_id(train_in_ls[i,]), overwrite = TRUE)
    file = assign(train_in_ls$name[i], fread(train_in_ls$name[i],  encoding="UTF-8" ))
    
    file$DAT =file$DAT+1
    file$case = rep(i, nrow(file))
    final = rbind(final, file)
    cat(i,"번째","완료","^^" ,"\n")
}
#2.train_target
train_target_id = drive_ls("2022_03/data",  pattern="train_target") $id
train_target_ls = drive_ls(path = as_id(train_target_id))
train_target_ls %<>% arrange(name)


final_target <- NULL
for (i in 1:nrow(train_target_ls)){
    drive_download(as_id(train_target_ls[i,]), overwrite = TRUE)
    file = assign(train_target_ls$name[i], fread(train_target_ls$name[i],  encoding="UTF-8" ))
    
    file$case = rep(i, nrow(file))
    final_target = rbind(final_target, file)
    cat(i,"번째","완료","@@" ,"\n")
}

```

# 1.결측치
```{r 결측치처리}
final[내부온도관측치<4 | 내부온도관측치>40,내부온도관측치 := NA]
final[내부습도관측치<0 | 내부습도관측치>100,내부습도관측치 := NA]
final[co2관측치<0 | co2관측치>1200, co2관측치 :=NA]
final[ec관측치<0 | ec관측치>8, ec관측치 :=NA]
final[시간당분무량<0 | 시간당분무량>3000,시간당분무량 := NA]
final[일간누적분무량<0 | 일간누적분무량>72000,일간누적분무량 := NA]
final[시간당백색광량<0 | 시간당백색광량>120000,시간당백색광량 := NA]
final[일간누적백색광량<0 | 일간누적백색광량>2880000,일간누적백색광량 := NA]
final[시간당적색광량<0 | 시간당적색광량>120000,시간당적색광량 := NA]
final[일간누적적색광량<0 | 일간누적적색광량>2880000,일간누적적색광량 := NA]
final[시간당청색광량<0 | 시간당청색광량>120000,시간당청색광량 := NA]
final[일간누적청색광량<0 |  일간누적청색광량>2880000, 일간누적청색광량 := NA]
final[시간당총광량<0 | 시간당총광량>120000,시간당총광량 := NA]
final[일간누적총광량<0 |  일간누적총광량>2880000,  일간누적총광량 := NA]
```


```{r 결측치탐색}
colSums(is.na(final))
final[is.na(내부온도관측치), .N, by=case]
final[is.na(co2관측치), .N, by=case]
final[is.na(시간당백색광량), .N, by=case]
final[is.na(시간당적색광량), .N, by=case]
final[is.na(시간당청색광량), .N, by=case]
final[is.na(시간당총광량), .N, by=case]
```

## 1-1. 시계열 오브젝트로 변경
```{r 시간 변수 조정}
#step1. 시간
final %>% mutate(new_obs_time = substr(obs_time,1,5),
    new_obs_time = parse_date_time(new_obs_time, orders="HM"),
    new_obs_time = case_when(
        grepl("[59]", new_obs_time) ~ new_obs_time + minut
        (1),
        TRUE ~ new_obs_time),
    hour = hour(new_obs_time),
    new_time = parse_date_time(paste0('2022-12-',as.character(DAT)," ",as.character(hour)), orders="ymdH")
    ) %>% 
    select(-obs_time,-new_obs_time) -> tmp

tmp %>% head
```

```{r}
par(mfrow=c(1,2))
plot_histogram(tmp[,-c('case','DAT','hour')])
plot_density(tmp[,-c('case','DAT','hour')])


cmp %>% mutate(case = as.factor(case)) ->cmp2


ggplot(cmp2) +
  aes(
    x = new_time,
    y = predicted_weight_g,
    colour = case,
    group = case
  ) +
  geom_line(size = 0.5) +
  scale_color_hue(direction = 1) +
  theme_gray()

```


## 1-2. 결측치 대체
```{r, 결측치대체-eda}
#내부온도관측치
par(mfrow=c(1,3))
tmp %>% filter(case == 4)  -> tmp_4
ggplot_na_distribution(tmp_4$내부온도관측치, title = "내부온도관측치", subtitle = "case_4" )
tmp %>% filter(case == 8)  -> tmp_8
ggplot_na_distribution(tmp_8$내부온도관측치,  title = "내부온도관측치", subtitle = "case_8")
tmp %>% filter(case == 26)  -> tmp_26
ggplot_na_distribution(tmp_26$내부온도관측치, title = "내부온도관측치", subtitle = "case_26")


#args(ggplot_na_distribution)

#co2관측치
tmp %>% filter(case == 1)  -> tmp_1
ggplot_na_distribution(tmp_1$co2관측치)
tmp %>% filter(case == 3)  -> tmp_3
ggplot_na_distribution(tmp_3$co2관측치)
tmp %>% filter(case == 4)  -> tmp_4
ggplot_na_distribution(tmp_4$co2관측치)
tmp %>% filter(case == 27) ->tmp_27 
ggplot_na_distribution(tmp_27$co2관측치)

```

```{r, 결측치대체-실행}

tmp %>% group_split(case)  %>%
  lapply(function(x){na_interpolation(x, option="spline")}) -> imp_list

data.table::rbindlist(imp_list) -> cmp
#imp_dt %>% is.na() %>% sum 
#cmp %>% head()
```


# 2. EDA
```{r, 변수중요도}
plot_correlation(cmp) # 강한 상관관계 발견됐지만 정말로 리니어한지 알 수 없음

```

```{r 변수중요도-리니어 확인}
theme = lattice::trellis.par.get()
theme$plot.symbol$col = rgb(.2, .2, .2, .4)
theme$plot.symbol$pch = 16
trellis.par.set(theme)



featurePlot(x = cmp[, c("일간누적분무량", "일간누적백색광량","일간누적총광량")] , 
            y = cmp$hour, 
            plot = "scatter", 
            type = c("p", "smooth"),
            span = 5,  
            layout = c(3, 1))


par(mfrow=c(1,2))
#1)0.88
featurePlot(x = cmp[,'시간당총광량'] , 
            y = cmp$시간당백색광량, 
            plot = "scatter", 
            type = c("p", "smooth"),
            span = 1,
            label= c("","시간당백색광량"))

#2)0.84 일간누적총광량, 일간누적백색광량 
featurePlot(x = cmp[, '일간누적총광량'], 
            y = cmp$일간누적백색광량, 
            plot = "scatter", 
            type = c("p", "smooth"),
            span = 5,
            label= c("","일간누적백색광량")
)
#3)0.66(일간누적적색광량,시간당적색광량) 
featurePlot(x = cmp[, '일간누적적색광량'], 
            y = cmp$시간당적색광량, 
            plot = "scatter", 
            type = c("p", "smooth"),
            span = 5,
            label= c("","시간당적색광량")
)


#4)0.0.61(일간누적청색광량,시간당청색광량) 
featurePlot(x = cmp[, '일간누적청색광량'], 
            y = cmp$시간당청색광량, 
            plot = "scatter", 
            type = c("p", "smooth"),
            span = 5,
            label= c("","시간당청색광량")
)


```

```{r, eda}

tmp %>% select(contains('광량')) %>%
  filter(일간누적총광량 == 0 | 일간누적백색광량 == 0) %>% summary


tmp %>% select(일간누적총광량, 일간누적백색광량) %>%
  filter(일간누적총광량 > 일간누적백색광량 )

tmp %>% select(일간누적총광량, 일간누적백색광량) %>%
  filter(일간누적백색광량 ==0 & 일간누적총광량 !=0)



tmp %>% select(일간누적총광량, 일간누적백색광량) %>%
  filter(일간누적백색광량 ==0 & 일간누적총광량 !=0)

tmp %>% head


#시간당총광량, 시간당백생광량
cmp %>% select(시간당총광량, 시간당백색광량) %>%
  filter(시간당총광량 == 시간당백색광량) %>% nrow()  # 10904
 
cmp %>% nrow #18816

cmp %>% select(시간당총광량, 시간당백색광량) %>%
  filter(시간당총광량 < 시간당백색광량) 

```


## 2-1. 타겟 병합
```{r, TARGET 병합}
# case->DAT별로target 머지 
for (i in 1:length(unique(cmp$case)) ){
  for (j in 1:length(unique(cmp$DAT)) ){
    cmp[case== i & DAT==j,'predicted_weight_g'] <- final_target[case == i & DAT== j,'predicted_weight_g']
  }
  cat(i,"번째","완료","\n")
}

cmp[,'predicted_weight_g'] = as.numeric(cmp$predicted_weight_g)

```


```{r, 타겟과의 상관관계}
plot_correlation(cmp) #중요한거없어보임

```

```{r, 케이스별 상관관계}
n = length(unique(cmp$case))
for (i in 1:n){
  plot_correlation(cmp[case==i, ], title = paste0("case_",i) )
} 

#케이스별 변수 분포
f = cmp[,c("case","내부온도관측치","내부습도관측치","co2관측치","ec관측치","시간당분무량","시간당백색광량", "시간당적색광량", "시간당청색광량")]
f %>% group_split(case) -> group_list

for (i in 1:n){
  plot_qq(group_list[[i]][,-1], title = paste0("case_",i))
} 

```


# 3. 피처엔지니어링

```{r}
#step1. 삭제
cmp %<>% select(-일간누적총광량, -시간당총광량)


cmp %>% select(case, DAT, hour, contains('누적')) %>%
  filter(hour == 23) %>%
  select(-hour) %>%
  rename(총누적분무량 = 일간누적분무량,
         총누적백색광량 = 일간누적백색광량,
         총누적적색광량 = 일간누적적색광량,
         총누적청색광량 = 일간누적청색광량) -> cmp_누적

#step2. 생성
feature = cmp[,c("case","DAT","내부온도관측치","내부습도관측치","co2관측치","ec관측치","시간당분무량","시간당백색광량", "시간당적색광량", "시간당청색광량")]
cmp_median = feature[,
                   lapply(.SD, median),
                   by=.(case, DAT)
                   ]

cmp_max = feature[,
                  lapply(.SD, max),
                  by=.(case, DAT)
                  ]

cmp_min = feature[,
                  lapply(.SD, min),
                  by=.(case, DAT)
                  ]

cmp_range = cmp_max - cmp_min

for (i in 1:ncol(cmp_median)){
  names(cmp_median)[i] = paste0("median_", names(cmp_median)[i])
  }

for (i in 1:ncol(cmp_range)){
  names(cmp_range)[i] = paste0("range_", names(cmp_range)[i])
}

#step3. 머지
cmp_agr = cbind(cmp_median[,-c(1:2)], cmp_range[,-c(1:2)], cmp_누적[,-c(1:2)])
cmp_agr[,'case'] = final_target$case
cmp_agr[,'DAT'] = final_target$DAT
```



```{r 최종 데이터셋 생성}
#step1. merge
setkey(cmp_agr, case,DAT)
setkey(final_target, case,DAT)

dt =final_target[cmp_agr]
names(dt) = gsub("시간당", "하루", names(dt))
#step2. order
DT = dt[,c(3,1,4:23,2)]
DT %>% head
```


#4. 테스트셋
```{r test}
#step1. test_input
test_in_id = drive_ls("2022_03/data",  pattern="test_input") $id
test_in_ls = drive_ls(path = as_id(test_in_id))
test_in_ls %<>% arrange(name)

test_input <- NULL
for (i in 1:nrow(test_in_ls)){
    drive_download(as_id(test_in_ls[i,]), overwrite = TRUE)
    file = assign(test_in_ls$name[i], fread(test_in_ls$name[i],  encoding="UTF-8" ))
    
    file$DAT =file$DAT+1
    file$case = rep(i, nrow(file))
    test_input = rbind(test_input, file)
    cat("test_input",i,"번째","완료","^^" ,"\n")
}

#step2. test_target
test_target_id = drive_ls("2022_03/data",  pattern="test_target") $id
test_target_ls = drive_ls(path = as_id(test_target_id))
test_target_ls %<>% arrange(name)


test_target <- NULL
for (i in 1:nrow(test_target_ls)){
    drive_download(as_id(test_target_ls[i,]), overwrite = TRUE)
    file = assign(test_target_ls$name[i], fread(test_target_ls$name[i],  encoding="UTF-8" ))
    
    file$case = rep(i, nrow(file))
    test_target = rbind(test_target, file)
    cat("teat_target",i,"번째","완료","@@" ,"\n")
}


```


```{r test basic eda}
test_input %>% summary()
plot_missing(test_input)

```


```{r}
test_input %>% summary()
plot_missing(test_input)

test_input[내부온도관측치<4 | 내부온도관측치>40,내부온도관측치 := NA]
test_input[내부습도관측치<0 | 내부습도관측치>100,내부습도관측치 := NA]
test_input[co2관측치<0 | co2관측치>1200, co2관측치 :=NA]
test_input[ec관측치<0 | ec관측치>8, ec관측치 :=NA]
test_input[시간당분무량<0 | 시간당분무량>3000,시간당분무량 := NA]
test_input[일간누적분무량<0 | 일간누적분무량>72000,일간누적분무량 := NA]
test_input[시간당백색광량<0 | 시간당백색광량>120000,시간당백색광량 := NA]
test_input[일간누적백색광량<0 | 일간누적백색광량>2880000,일간누적백색광량 := NA]
test_input[시간당적색광량<0 | 시간당적색광량>120000,시간당적색광량 := NA]
test_input[일간누적적색광량<0 | 일간누적적색광량>2880000,일간누적적색광량 := NA]
test_input[시간당청색광량<0 | 시간당청색광량>120000,시간당청색광량 := NA]
test_input[일간누적청색광량<0 |  일간누적청색광량>2880000, 일간누적청색광량 := NA]
test_input[시간당총광량<0 | 시간당총광량>120000,시간당총광량 := NA]
test_input[일간누적총광량<0 |  일간누적총광량>2880000,  일간누적총광량 := NA]

```

```{r, test }
test_input %>% mutate(new_obs_time = substr(obs_time,1,5),
    new_obs_time = parse_date_time(new_obs_time, orders="HM"),
    new_obs_time = case_when(
        grepl("[59]", new_obs_time) ~ new_obs_time + minutes(1),
        TRUE ~ new_obs_time),
    hour = hour(new_obs_time),
    new_time = parse_date_time(paste0('2022-12-',as.character(DAT)," ",as.character(hour)), orders="ymdH")
    ) %>% 
    select(-obs_time,-new_obs_time) -> tmp_test

tmp_test %>% group_split(case)  %>%
  lapply(function(x){na_interpolation(x, option="spline")}) -> imp_list_test

data.table::rbindlist(imp_list_test) -> cmp_test

```


```{r}
#step1. 삭제
cmp_test %<>% select(-일간누적총광량, 시간당총광량)

cmp_test %>% select(case, DAT, hour, contains('누적')) %>%
  filter(hour == 23) %>%
  select(-hour) %>%
  rename(총누적분무량 = 일간누적분무량,
         총누적백색광량 = 일간누적백색광량,
         총누적적색광량 = 일간누적적색광량,
         총누적청색광량 = 일간누적청색광량) -> cmp_test_누적

#step2. 생성
feature = cmp_test[,c("case","DAT","내부온도관측치","내부습도관측치","co2관측치","ec관측치","시간당분무량","시간당백색광량", "시간당적색광량", "시간당청색광량")]
cmp_test_median = feature[,
                   lapply(.SD, median),
                   by=.(case, DAT)
                   ]

cmp_test_max = feature[,
                  lapply(.SD, max),
                  by=.(case, DAT)
                  ]

cmp_test_min = feature[,
                  lapply(.SD, min),
                  by=.(case, DAT)
                  ]

cmp_test_range = cmp_test_max - cmp_test_min

for (i in 1:ncol(cmp_test_median)){
  names(cmp_test_median)[i] = paste0("median_", names(cmp_test_median)[i])
  }


for (i in 1:ncol(cmp_test_range)){
  names(cmp_test_range)[i] = paste0("range_", names(cmp_test_range)[i])
}


cmp_test_agr = cbind(cmp_test_median[,-c(1:2)], cmp_test_range[,-c(1:2)], cmp_test_누적[,-c(1:2)])
cmp_test_agr[,'case'] = test_target$case
cmp_test_agr[,'DAT'] = test_target$DAT


#step2 merge
setkey(cmp_test_agr, case,DAT)
setkey(test_target, case,DAT)

dt_test =test_target[cmp_test_agr]
names(dt_test) = gsub("시간당", "하루", names(dt_test))

#step3 order
DT_test = dt_test[,c(3,1,4:23,2)]

DT_test  %>% head
DT %>% head
```


#5. 스케일링(r회귀분석에서만 씀, python은 파이프라인 생성)
```{r, 스케일}
min_max_norm = preProcess(DT[,-c(23)], method = c("range"))

DT_scaled = predict(min_max_norm, DT)
DT_test_scaled = predict(min_max_norm, DT_test)
DT_test_scaled  %>% head
DT_scaled %>% head

```

# 6. 저장
```{r}
DT %>% write.csv("train_final.csv", row.names=FALSE)
DT_test %>% write.csv("test_final.csv", row.names=FALSE)

drive_upload("train_final.csv",
             path = "2022_03/data/train_final.csv",
             overwrite = TRUE)

drive_upload("test_final.csv",
             path = "2022_03/data/test_final.csv",
             overwrite = TRUE)

```
